# Generated by Django 5.2.5 on 2025-10-07 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="크롤링 소스의 레시피 ID", max_length=50, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("source_url", models.URLField(blank=True, max_length=512, null=True)),
                ("servings", models.CharField(blank=True, max_length=50)),
                ("cook_time", models.CharField(blank=True, max_length=50)),
                ("difficulty", models.CharField(blank=True, max_length=50)),
                ("copyright_holder", models.CharField(blank=True, max_length=100)),
                (
                    "tips",
                    models.JSONField(
                        blank=True, default=list, help_text="요리 팁 목록"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="재료명", max_length=255)),
                (
                    "quantity",
                    models.CharField(blank=True, help_text="양", max_length=100),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(help_text="조리 단계 순서")),
                ("instruction", models.TextField(help_text="조리 방법 설명")),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipe", "order"), name="unique_recipe_step_order"
                    )
                ],
            },
        ),
    ]
