# Generated by Django 4.2.25 on 2025-10-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                ("chunk_id", models.TextField(primary_key=True, serialize=False)),
                ("step_no", models.IntegerField(blank=True, null=True)),
                ("section", models.TextField(blank=True, null=True)),
                ("text", models.TextField()),
                ("meta_json", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "chunk",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RecipeDoc",
            fields=[
                (
                    "recipe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="recipes.recipe",
                    ),
                ),
                ("source_url", models.TextField(blank=True, null=True)),
                ("raw_json", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "recipe_doc",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="step",
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="ChunkEmbeddingMeta",
            fields=[
                (
                    "chunk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="recipes.chunk",
                    ),
                ),
                ("model_name", models.TextField()),
                ("dim", models.IntegerField()),
                ("created_at", models.TextField(blank=True, null=True)),
                ("faiss_vector_id", models.IntegerField(unique=True)),
            ],
            options={
                "db_table": "chunk_embedding_meta",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
