# Generated by Django 4.2.25 on 2025-10-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_chunk_recipedoc_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="recipe",
            table="recipe",
        ),
        migrations.AlterModelTable(
            name="step",
            table="step",
        ),
    ]
