# Generated by Django 4.2.26 on 2025-11-20 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_table_alter_step_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeVoicePlan",
            fields=[
                (
                    "recipe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="recipes.recipe",
                    ),
                ),
                ("plan_json", models.TextField()),
                ("created_at", models.TextField(blank=True, null=True)),
                ("updated_at", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "recipe_voice_plan",
                "managed": False,
            },
        ),
    ]
